# Generated by Django 5.0.3 on 2024-03-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('place', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('time_create', models.TimeField(auto_now_add=True)),
                ('time_update', models.TimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
