# Generated by Django 5.0.3 on 2024-03-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobots',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterField(
            model_name='cobots',
            name='event',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cobots',
            name='is_approved',
            field=models.BooleanField(blank=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='cobots',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='cobots',
            name='place',
            field=models.CharField(max_length=500, verbose_name='Ссылка'),
        ),
    ]
