# Generated by Django 5.0.3 on 2024-03-07 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobots', '0002_alter_cobots_options_alter_cobots_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobots',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ведущий'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='ChatID')),
                ('text', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobots.cobots', verbose_name='Название')),
            ],
        ),
    ]
