# Generated by Django 5.0.3 on 2024-03-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobots', '0003_alter_cobots_name_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobots',
            name='user_chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
