# Generated by Django 5.0.3 on 2024-03-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobots', '0004_cobots_user_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobots',
            name='is_approved',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Статус'),
        ),
    ]
