# Generated by Django 5.0.3 on 2024-03-08 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobots', '0005_alter_cobots_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobots',
            name='user_chat_id',
        ),
    ]
