# Generated by Django 5.0.3 on 2024-03-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobots', '0006_remove_cobots_user_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobots',
            name='user_chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
